{{- if not .Values.skip.olefy }}
{{- $c := "olefy" }}
{{- $v := .Values.olefy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailcow.fullname" . }}-{{ $c }}
  labels:
    {{- include "mailcow.labels" (dict "root" . "component" $c) | nindent 4 }}
spec:
  replicas: 1
  {{- include "mailcow.strategy" "RollingUpdate" | nindent 2 }}
  selector:
    matchLabels:
      {{- include "mailcow.selectorLabels" (dict "root" . "component" $c) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mailcow.labels" (dict "root" . "component" $c) | nindent 8 }}
      {{- with include "mailcow.podDefaultAnnotations" . }}
      {{- . | nindent 6 }}
      {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- include "mailcow.podCommon" (dict "root" .) | nindent 6 }}
      containers:
        - name: olefy-mailcow
          image: {{ include "mailcow.image" $v.image }}
          imagePullPolicy: {{ $v.image.pullPolicy }}
          env:
            {{- include "mailcow.env.tz" . | nindent 12 }}
            - {name: OLEFY_BINDADDRESS, value: "0.0.0.0"}
            - {name: OLEFY_BINDPORT, value: "10055"}
            - {name: OLEFY_TMPDIR, value: /tmp}
            - {name: OLEFY_PYTHON_PATH, value: /usr/bin/python3}
            - {name: OLEFY_OLEVBA_PATH, value: /usr/bin/olevba}
            - {name: OLEFY_LOGLVL, value: "20"}
            - {name: OLEFY_MINLENGTH, value: "500"}
            - {name: OLEFY_DEL_TMP, value: "1"}
            - {name: SKIP_OLEFY, value: "n"}
          ports:
            - name: olefy
              containerPort: 10055
          {{- include "mailcow.tcpProbes" (dict "port" 10055 "startup" 30) | nindent 10 }}
          resources:
            {{- toYaml $v.resources | nindent 12 }}
{{- end }}
